[package]
name = "portfolio"
version = "0.1.0"
authors = ["dohaicuong <beatyshot@gmail.com>"]
edition = "2018"
[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
stdweb = "0.4"
yew = { version = "0.9.2" }

[lib]
name = "portfolio"
path = "src/lib.rs"